gui:
  spinner:
    frames:
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    rate: 30
