gui:
  spinner:
    frames:
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
      - ' '
    rate: 30

  # https://github.com/catppuccin/lazygit/blob/main/themes/frappe/sapphire.yml
  theme:
    activeBorderColor:
      - '#85c1dc'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#85c1dc'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'
  authorColors:
    '*': '#babbf1'

customCommands:
  - key: 'n'
    context: localBranches
    description: 'New branch'
    prompts:
      - type: 'input'
        title: 'What is the branch name?'
        key: 'BranchName'
        initialValue: ''
      - type: 'input'
        title: 'What it the prefix?'
        key: 'Prefix'
        initialValue: ''
    command: 'git start {{.Form.Prefix}} {{.Form.BranchName}}'
    loadingText: 'Creating Branch'
