#!/bin/bash

has() {
  command -v "$1" 1>/dev/null 2>&1
}

PACKAGE_MANAGER=
INSTALL=
UPDATE=

PLATFORM="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [[ "$PLAYFORM" == "darwin" ]]; then
    PACKAGE_MANAGER="brew"
    INSTALL="install"
    UPDATE="update"
else
    PACKAGE_MANAGER="apt"
    INSTALL="install -y"
    UPDATE="update"
fi

installHomebrew() {
    echo
    echo "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

installCliTools() {
    echo
    echo "Install Cli Tools with $PACKAGE_MANAGER"

    while read tool; do
        IFS=' '; VALUE=($tool); unset IFS;
        IFS=','; TOOL=(${VALUE[0]}); unset IFS;

        if [ -z ${TOOL[1]+x} ]; then
            BIN_NAME=${TOOL[0]};
        else
            BIN_NAME=${TOOL[1]}
        fi

        echo
        if [ -z ${VALUE[1]+x} ]; then
            if has ${BIN_NAME}; then
                echo "Updating ${TOOL[0]}"
                $PACKAGE_MANAGER $UPDATE ${TOOL[0]}
            else
                echo "Install ${TOOL[0]}"
                $PACKAGE_MANAGER $INSTALL ${TOOL[0]}
            fi
        else
            if ! has ${BIN_NAME}; then
                echo "Install ${TOOL[0]}"
                curl -sS ${VALUE[1]} | sh -s -- -y
            fi
        fi
    done < ./script/cli-tools
}

installCasks() {
    echo
    echo "Install Casks"

    while read cask; do
        IFS=' '; VALUE=($cask); unset IFS;

        echo
        if has $cask; then
            echo "Updating $cask"
            brew update $cask
        else
            echo "Install $cask"
            $PACKAGE_MANAGER $INSTALL --cask $cask
        fi
    done < ./script/casks
}
