#!/bin/bash

installHomebrew() {
    echo "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

installCliTools() {
    echo "Install Cli Tools"
    while read p; do
        echo "Install $p"
    done < ./script/cli-tools
}
