#!/bin/bash

echo "Setup a new environment"

source ./script/install

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [[ "$platform" == "darwin" ]]; then
    installHomebrew
fi

installCliTools
installCasks

echo
echo "Handle zsh plugins"
installZshPlugin fzf-tab master https://github.com/Aloxaf/fzf-tab.git

gh config set git_protocol ssh
gh config set browser open
gh auth login

# Install NodeJS
fnm install --lts
fnm use

# Prevent Last login message
touch $HOME/.hushlogin

source ./script/stow
