#!/bin/bash

echo "Setup a new environment"

source ./script/install

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [[ "$platform" == "darwin" ]]; then
    installHomebrew
fi

installCliTools
installCasks

installZshPlugin fzf-tab main https://github.com/Aloxaf/fzf-tab.git

# Install NodeJS
fnm install --lts
fnm use

echo "Create .conf directory"
mkdir $HOME/.config
mkdir $HOME/.config/zsh
mkdir $HOME/.config/nvim
mkdir $HOME/.config/ghostty

echo 'Run stow commands'
stow --target=../.config/nvim nvim
stow --target=../.config starship
stow --target=$HOME/.config/ghostty ghostty
stow zsh

source $HOME/.zshrc
