#!/bin/bash

source ./script/install

# installHomebrew
installCliTools

# Create dir to contain config
mkdir ~/.config

mkdir ~/.config/zsh
mkdir ~/.config/nvim

# Run stow for each package
stow --target=../.config/nvim nvim
stow zsh
stow starship
