#!/bin/bash

mkdir -p $HOME/.config/zsh
mkdir -p $HOME/.config/fzf
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/ghostty
mkdir -p $HOME/.config/lazygit
mkdir -p $HOME/.config/skhd

echo 'Run stow commands'
stow zsh
stow --target=$HOME/.config starship
stow --target=$HOME/.config/fzf fzf 
stow --target=$HOME/.config/nvim nvim
stow --target=$HOME/.config/ghostty ghostty
stow --target=$HOME/.config/lazygit lazygit
stow --target=$HOME/.config/skhd skhd

