#!/bin/bash

mkdir -p $HOME/.config/bat
mkdir -p $HOME/.config/zsh
mkdir -p $HOME/.config/fzf
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/ghostty
mkdir -p $HOME/.config/lazygit

echo 'Run stow commands'
stow zsh
stow --target=$HOME/.config/bat bat
stow --target=$HOME/.config starship
stow --target=$HOME/.config/fzf fzf 
stow --target=$HOME/.config/nvim nvim
stow --target=$HOME/.config/ghostty ghostty
stow --target=$HOME/.config/lazygit lazygit

