#!/bin/bash

mkdir -p $HOME/.config/bat
mkdir -p $HOME/.config/eza
mkdir -p $HOME/.config/fzf
mkdir -p $HOME/.config/ghostty
mkdir -p $HOME/.config/kitty
mkdir -p $HOME/.config/lazygit
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/zsh

echo 'Run stow commands'
stow --target=$HOME/.config/bat bat
stow --target=$HOME/.config/eza eza
stow --target=$HOME/.config/fzf fzf 
stow --target=$HOME/.config/ghostty ghostty
stow git
stow --target=$HOME/.config/kitty kitty 
stow --target=$HOME/.config/lazygit lazygit
stow --target=$HOME/.config/nvim nvim
stow --target=$HOME/.config starship
stow zsh

