#!/bin/bash

source ./script/install

echo "Update dotfiles"

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [[ "$platform" == "darwin" ]]; then
    installHomebrew
fi

installCliTools
installCasks

installZshPlugin fzf-tab main https://github.com/Aloxaf/fzf-tab.git
