#!/bin/bash

source ./script/install

echo "Update dotfiles"

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [[ "$platform" == "darwin" ]]; then
    installHomebrew
fi

installCliTools
installCasks

echo
echo "Handle zsh plugins"
installZshPlugin fzf-tab master https://github.com/Aloxaf/fzf-tab.git
