#!/bin/bash

if [[ $1 == '-' || $1 == '--' || $1 == '-b' || $1 == 'master' || $1 == 'main' ]]; then
  git checkout $@
  exit 0
fi

BRANCH="$(git branch --all | fzf --query "$1" -1 | tr -d '* ')"

if [[ "$BRANCH" != '' ]]; then
  git checkout "${BRANCH#remotes/origin/}"
fi

